# Generated by Django 3.1.7 on 2021-06-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyTasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
                ('courseIdC', models.CharField(max_length=10)),
                ('courceName', models.CharField(max_length=30)),
                ('courseFee', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.CharField(max_length=10)),
                ('studentName', models.CharField(max_length=30)),
                ('courseIdS', models.CharField(max_length=15)),
            ],
        ),
    ]
